### ISSUE TITLE
Reason for bump in number of master nodes in v0.21?

### ISSUE THREAD

**Issue by aegershman** [starkandwayne/cfcr-compiled-deployment#1]
I am upgrading from v0.16 to v0.21. [Any reason why cfcr v0.21 bumps the number of `master` nodes from 1 to 3?](https://github.com/starkandwayne/cfcr-compiled-deployment/blob/v0.21.0/cfcr.yml#L129). I would like to override the value down to 1, but just want to make sure I'm not going to screw everything up.

Thanks a ton

**Comment by drnic** [comment]
I think they were just encouraging a multi master deployment by default.


________________________________

**Comment by aegershman** [comment]
Ah. Yep, that was silly of me. Thanks!
